// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fetch_feeds_by_url.sql

package database

import (
	"context"
)

const feedByURL = `-- name: FeedByURL :one
SELECT id, created_at, updated_at, name, url, user_id
FROM feed
WHERE url=$1
`

func (q *Queries) FeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, feedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
