// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mark_fetched_field.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const markFetchedFeed = `-- name: MarkFetchedFeed :exec
UPDATE feed
SET last_fetched_at=NOW(), updated_at=NOW()
WHERE id=$1
`

func (q *Queries) MarkFetchedFeed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markFetchedFeed, id)
	return err
}
