// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: unfollow_feed.sql

package database

import (
	"context"
)

const unfollowFeed = `-- name: UnfollowFeed :exec
DELETE FROM feed_follows
USING users, feed
WHERE feed_follows.user_id = users.id
AND feed_follows.feed_id = feed.id
AND users.name = $1 
AND feed.url = $2
`

type UnfollowFeedParams struct {
	Name string
	Url  string
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeed, arg.Name, arg.Url)
	return err
}
